ARG version
FROM almalinux:${version:-9}
#RUN cat/etc/*release
ARG course=docker
ARG trainer=mounika
ARG Duration=20hrs
env Duration=${Duration}
RUN echo "course is ${course}, tariner is ${trainer} , env is ${duration}"
CMD ["sleep","200"]
