ARG version
FROM almalinux:${version:-9}
#RUN cat/etc/*release
ARG course=docker
ARG trainer=mounika
env duration=10hrs
RUN echo "course is ${course}, tariner is ${trainer} , env is ${trainer}"
CMD ["sleep","200"]
